version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:16-alpine
    container_name: brandgames-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brandgames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nuxt приложение (для разработки)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: brandgames-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/brandgames?schema=public
      JWT_SECRET: your-secret-key-change-in-production
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:

